### ISSUE TITLE
Error on gulp:default

### ISSUE THREAD

**Issue by thomasklein** [greypants/gulp-starter#114]
Hi! First of all, thanks for gulp-starter, really like it! 

However, I just ran into a problem with the default gulp task. The complete stack is:
```
[10:32:46] Using gulpfile ~/Documents/fun/gulp-starter/gulpfile.js
[10:32:46] Starting 'sass'...
[10:32:46] Starting 'images'...
[10:32:46] Starting 'markup'...
[10:32:46] Starting 'watchify'...
[10:32:46] Watching files required by global.js
[10:32:46] Bundling global.js...
[10:32:46] Watching files required by page.js
[10:32:46] Bundling page.js...
[10:32:46] Starting 'browserSync'...
[10:32:46] Finished 'browserSync' after 16 ms
path.js:422
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.posix.resolve (path.js:422:13)
    at Deps._transform (/Users/thomas/Documents/fun/gulp-starter/node_modules/browserify/node_modules/module-deps/index.js:84:53)
    at Deps.Transform._read (/Users/thomas/Documents/fun/gulp-starter/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Deps.Transform._write (/Users/thomas/Documents/fun/gulp-starter/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at Labeled.Pipeline._write (/Users/thomas/Documents/fun/gulp-starter/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:72:22)
    at doWrite (/Users/thomas/Documents/fun/gulp-starter/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/Users/thomas/Documents/fun/gulp-starter/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Labeled.Writable.write (/Users/thomas/Documents/fun/gulp-starter/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at Labeled.ondata (/Users/thomas/Documents/fun/gulp-starter/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:572:20)
    at Labeled.emit (events.js:107:17)
```

I used the master branch (latest commit: e56fedc6110917339f4c0747a5ab3f184b750872) and tried an npm update, just in case, but it didn't work either.

Hope you can help me out on this.

Cheers,
Thomas

**Comment by greypants** [comment]
hmm... Looking into it to see if I can reproduce. In the meantime, try the 2.0 branch - I'll be merging that in soon.

**Comment by greypants** [comment]
Can't reproduce. I cleared out all my node_modules and tried running it fresh. I'm on node v0.10.36, and npm 2.3.0.

Let me know if you make any progress on this!
